ticket 8.1
charli353/NCNEWS pull request #1
Opened 2023-07-19 10:31 UTC by charli353

2023-07-19 10:58 UTC, Beth-McCormack requested changes
Please see comment I've left and resubmit when this is done🙂

2023-07-19 10:58 UTC, Beth-McCormack commented on src/components/Article.jsx
> +          getComments(currentId).then((response) => {
In this onSubmit, you shouldn't be making an api call, this should be happening in a useEffect. It is more efficiently to only reset the comments in the onSubmit.

2023-07-20 07:57 UTC, sirKevlar commented on src/componentfuncs/Comments.jsx
> +
This is a strange variable name (commentValidate)... Is this function's only job to validate a comment?

2023-07-20 07:57 UTC, sirKevlar commented on src/componentfuncs/Comments.jsx
> +      postComment(currentId, comment)
What happens if the post fails? In order to complete this ticket, we need to handle the possibility of error upon posting

2023-07-20 07:57 UTC, sirKevlar commented on src/componentfuncs/Comments.jsx
> +          <FailedForm valid={validity}/>
An onClick here isn't good for accessibility reasons. ATM only mouse users can use your posting function. How could we make this accessible to keyboard users (maybe a listener on the form would help?). We need to change this to complete this ticket please

2023-07-20 07:57 UTC, sirKevlar commented on src/componentfuncs/Comments.jsx
> +function FailedForm (props) {
Failed implies an error. I think this func should be called invalidForm

2023-07-20 07:57 UTC, sirKevlar commented on src/App.css
> +  color: #F4EEE0;
The responsive design on this app is a little strange. In larger views all of the content is squeezed in to the first third of the screen with the other 2 thirds empty. Also the comments section is very easy to break by squeezing screen size. I think you should play with the responsiveness to check all screen sizes work

2023-07-20 12:39 UTC, RichardNeat requested changes
Nice work so far on this one. Just a few points to address please:
- I am getting an error when I begin a typing a new comment, could you take a look and correct please. Currently this means I can't see my comment being posted, nor when it refreshes. Make sure this comment renders at the top of the list when submitted.
- Consider what happens on a slow connection to make sure the user cannot click submit multiple times.
- Ensure that the error handling functions as expected.
- Please avoid using divs

Have a look at these and then resubmit when you're ready.

2023-07-20 12:39 UTC, RichardNeat commented on src/componentfuncs/Comments.jsx
> +      <div id='commentarea'>
Could we use any better html tag here than a div? And anywhere else you may have used a div.

2023-07-20 14:17 UTC, mezzDavies requested changes
You are so close. It works! But I cannot let it pass as you are using a boolean in a very inadvisable way. Please see my comment below and read the notes [here](https://notes.northcoders.com/courses/js-front-end/error-handling) and I think you'll be able to fix it 👍

2023-07-20 14:17 UTC, mezzDavies commented on src/components/Article.jsx
> +      <text id='articleimg'>
I'm a bit confused by this `<text>` tag. It is currently leading to an error - "The tag `<text>` is unrecognized in this browser." Could you just add the id to the `img` tag instead and do without the `<text>` one (is it actually a tag 🤷 😄 )

2023-07-20 14:17 UTC, mezzDavies commented on src/componentfuncs/Comments.jsx
> +        setValid('Network Error, Try Again')
Although this is working you are changing the data type of validity here. Its initial state is a boolean of true and you set it's state to false elsewhere. Changing it to a string is is not good practice. I would strongly suggest you find another way to get the error message rendered on screen.

2023-07-20 14:41 UTC, merged